GET http://localhost:8000/methods/get
HTTP 200

HEAD http://localhost:8000/methods/head
HTTP 200

POST http://localhost:8000/methods/post
HTTP 200

PUT http://localhost:8000/methods/put
HTTP 200

DELETE http://localhost:8000/methods/delete
HTTP 200

CONNECT http://localhost:8000/methods/connect
HTTP 200

OPTIONS http://localhost:8000/methods/options
HTTP 200

TRACE http://localhost:8000/methods/trace
HTTP 200

PATCH http://localhost:8000/methods/patch
HTTP 200

LINK http://localhost:8000/methods/link
HTTP 200

UNLINK http://localhost:8000/methods/unlink
HTTP 200

PURGE http://localhost:8000/methods/purge
HTTP 200

LOCK http://localhost:8000/methods/lock
HTTP 200

UNLOCK http://localhost:8000/methods/unlock
HTTP 200

PROPFIND http://localhost:8000/methods/propfind
HTTP 200

VIEW http://localhost:8000/methods/view
HTTP 200
