version: 2.1

jobs:
  test-ubuntu-arm64:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Environment
          command: |
            bin/environment.sh
      - run:
          name: Install prerequisites
          command: |
            bin/install_prerequisites_ubuntu.sh
            sudo apt update -qq
            sudo apt install -y -qq libxml2-dev libxslt-dev libxml2-utils libcurl4-openssl-dev
      - run:
          name: Install rust
          command: |
            bin/install_rust.sh
      - run:
          name: Tests units
          command: |
            bin/test/test_prerequisites.sh
            bin/test/test_unit.sh
      - run:
          name: Build release
          command: |
            bin/release/release.sh
      - run:
          name: Integration tests
          command: |
            PATH="${PWD}/target/release:${PATH}"
            export PATH
            bin/test/test_prerequisites.sh
            bin/test/test_integ.sh
      - store_artifacts:
          path: integration/build/*.log

workflows:
  tests-arm64:
    jobs:
      - test-ubuntu-arm64
