#!/bin/bash

set -e
set -u

OUTPUT_DIR="$1"
OS="$2"
RELEASE_DIR=$PWD/target/release
MAN_DIR=$PWD/target/man
VERSION=$(grep '^version' Cargo.toml | cut -f2 -d'"')
PACKAGE_DIR="hurl-$VERSION"
TARBALL_FILE="hurl-$VERSION-x86_64-$OS.tar.gz"

mkdir -p "$OUTPUT_DIR"
echo create tarballs into "$OUTPUT_DIR"
cd "$OUTPUT_DIR"

rm -rf "$PACKAGE_DIR"
mkdir "$PACKAGE_DIR"

cp "$RELEASE_DIR/hurl" "$PACKAGE_DIR"
cp "$RELEASE_DIR/hurlfmt" "$PACKAGE_DIR"
cp "$MAN_DIR"/* "$PACKAGE_DIR"

tar cvfz "$TARBALL_FILE" "$PACKAGE_DIR"
rm -rf "$PACKAGE_DIR"


