POST http://localhost:8000/post-xml
<?xml version="1.0"?>
<drink>café</drink>
HTTP 200


POST http://localhost:8000/post-xml-no-prolog
<drink>café</drink>
HTTP 200


POST http://localhost:8000/post-xml-large
<?xml version='1.0' ?>
<root>
    <listing>
        <seller_info>
            <seller_name></seller_name>
            <seller_rating></seller_rating>
        </seller_info>
        <payment_types>
        </payment_types>
        <shipping_info>
        </shipping_info>
        <buyer_protection_info>
        </buyer_protection_info>
        <auction_info>
            <current_bid></current_bid>
            <time_left></time_left>
            <high_bidder>
                <bidder_name>MH of San Francisco,</bidder_name>
                <bidder_rating></bidder_rating>
            </high_bidder>
            <num_items>
                8
            </num_items>
            <num_bids></num_bids>
            <started_at>$9</started_at>
            <bid_increment>$10</bid_increment>
            <location></location>
            <opened></opened>
            <closed>Mon Nov 27, 2:00 pm PT</closed>
            <id_num>
                3699803
            </id_num>
            <notes></notes>
        </auction_info>
        <bid_history>
            <highest_bid_amount>
                $2459
            </highest_bid_amount>
            <quantity>1</quantity>
        </bid_history>
        <item_info>
            <memory></memory>
            <hard_drive></hard_drive>
            <cpu>
                900MHz
            </cpu>
            <brand>HP Pavilion</brand>
            <description>The Pavilion 9780C gives you
                everything you need in a home
                PC, from the exhilarating
                multimedia experience of DVD to
                the customized music-making
                abilities of the HP CD-Writer
                Plus - it's all in a hot
                translucent blue case! Monitor
                not included.


            </description>
        </item_info>
    </listing>

    <listing>
        <seller_info>
            <seller_name></seller_name>
            <seller_rating></seller_rating>
        </seller_info>
        <payment_types>
        </payment_types>
        <shipping_info>
        </shipping_info>
        <buyer_protection_info>
        </buyer_protection_info>
        <auction_info>
            <current_bid></current_bid>
            <time_left></time_left>
            <high_bidder>
                <bidder_name></bidder_name>
                <bidder_rating></bidder_rating>
            </high_bidder>
            <num_items></num_items>
            <num_bids></num_bids>
            <started_at></started_at>
            <bid_increment></bid_increment>
            <location></location>
            <opened></opened>
            <closed></closed>
            <id_num></id_num>
            <notes></notes>
        </auction_info>
        <bid_history>
            <highest_bid_amount>
            </highest_bid_amount>
            <quantity></quantity>
        </bid_history>
        <item_info>
            <memory></memory>
            <hard_drive></hard_drive>
            <cpu></cpu>
            <brand></brand>
            <description>
            </description>
        </item_info>
    </listing>

    <listing>
        <seller_info>
            <seller_name></seller_name>
            <seller_rating></seller_rating>
        </seller_info>
        <payment_types>
        </payment_types>
        <shipping_info>
        </shipping_info>
        <buyer_protection_info>
        </buyer_protection_info>
        <auction_info>
            <current_bid></current_bid>
            <time_left></time_left>
            <high_bidder>
                <bidder_name></bidder_name>
                <bidder_rating></bidder_rating>
            </high_bidder>
            <num_items></num_items>
            <num_bids></num_bids>
            <started_at></started_at>
            <bid_increment></bid_increment>
            <location></location>
            <opened></opened>
            <closed></closed>
            <id_num></id_num>
            <notes></notes>
        </auction_info>
        <bid_history>
            <highest_bid_amount>
            </highest_bid_amount>
            <quantity></quantity>
        </bid_history>
        <item_info>
            <memory></memory>
            <hard_drive></hard_drive>
            <cpu></cpu>
            <brand></brand>
            <description>
            </description>
        </item_info>
    </listing>

    <listing>
        <seller_info>
            <seller_name>tx of Santa Clara</seller_name>
            <seller_rating></seller_rating>
        </seller_info>
        <payment_types>
        </payment_types>
        <shipping_info>
        </shipping_info>
        <buyer_protection_info>
        </buyer_protection_info>
        <auction_info>
            <current_bid></current_bid>
            <time_left></time_left>
            <high_bidder>
                <bidder_name></bidder_name>
                <bidder_rating></bidder_rating>
            </high_bidder>
            <num_items>2</num_items>
            <num_bids></num_bids>
            <started_at></started_at>
            <bid_increment></bid_increment>
            <location></location>
            <opened></opened>
            <closed>Mon Nov 27, 2:30 pm PT</closed>
            <id_num>
                3699948
            </id_num>
            <notes></notes>
        </auction_info>
        <bid_history>
            <highest_bid_amount>
                $3837
            </highest_bid_amount>
            <quantity>2</quantity>
        </bid_history>
        <item_info>
            <memory>128MB high-performance PC133 ECC SDRAM Maximum: 4GB memory
                capacity (3.3GB maximum usable memory)
            </memory>
            <hard_drive>Open bay - none installed or includedSupports 9.1GB and 18.2GB 7,200rpm Ultra2
                SCSI disk drivesSupports 9.1GB, 18.2GB, and 36.4GB 10,000rpm Ultra2 SCSI disk
                drives
            </hard_drive>
            <cpu>Intel Pentium III 800MHz</cpu>
            <brand>Hewlett Packard NetServer LH3000 Pentium III 800MHz
                128MB RAM/Open Bay/32X CD/No OS
            </brand>
            <description>
                HP NetServer LH 3000 Pentium III 800MHzThis rack mount HP
                NetServer LH 3000 brings higher performance and reliability to
                meet your demanding departmental server requirements.
                Incorporating performance, storage, and high-availability
                technologies, this workhorse is loaded with features you'd
                expect only in high-end servers.Key Features At a Glance:
                Extraordinary performance -- dual Intel Pentium III processor
                capability (one 800MHz processor included)- with 133MHz front
                side bus, PC 133MHz ECC SDRAM, and performance-boosting
                integrated RAID controller. Best-in-class reliability and
                uptime -- with fully hot-swappable/hot-pluggable components,
                including disk drives, power supplies, fans, and hot-plug PCI
                slots. Includes widely adopted, fault-tolerant RAID 5
                technology-using an embedded, dual-channel NetRAID controller
                with optional battery backup, hardware-based parity (XOR)
                logic, and 32MB cache-expandable to 128MB. Excellent
                investment protection -- the HP NetServer LH 3000's design
                makes it easily upgradable as higher scalability Xeon servers
                and new processor enhancements become available. HP OpenView
                ManageX Event Manager -- for simplified NOS and high
                availability system management. Intelligent management -- a
                comprehensive tool set to monitor your server hardware and
                software from anywhere, anytime. Simple installation-rack
                mount form factor version.
            </description>
        </item_info>
    </listing>

    <listing>
        <seller_info>
            <seller_name></seller_name>
            <seller_rating></seller_rating>
        </seller_info>
        <payment_types>
        </payment_types>
        <shipping_info>
        </shipping_info>
        <buyer_protection_info>
        </buyer_protection_info>
        <auction_info>
            <current_bid></current_bid>
            <time_left></time_left>
            <high_bidder>
                <bidder_name>LW of Sugar Land</bidder_name>
                <bidder_rating></bidder_rating>
            </high_bidder>
            <num_items>1</num_items>
            <num_bids></num_bids>
            <started_at>
                $9
            </started_at>
            <bid_increment>
                $20
            </bid_increment>
            <location></location>
            <opened></opened>
            <closed>
                Mon Nov 27, 2:30 pm PT
            </closed>
            <id_num>3699893</id_num>
            <notes></notes>
        </auction_info>
        <bid_history>
            <highest_bid_amount>$2392
            </highest_bid_amount>
            <quantity></quantity>
        </bid_history>
        <item_info>
            <memory></memory>
            <hard_drive></hard_drive>
            <cpu></cpu>
            <brand>Hewlett Packard NetServe</brand>
            <description>Refurbished and warranted by
                manufacturer! Dual processing
                capability (one 800MHz Pentium
                III processor provided)!!!
            </description>
        </item_info>
    </listing>

    <listing>
        <seller_info>
            <seller_name></seller_name>
            <seller_rating></seller_rating>
        </seller_info>
        <payment_types>
        </payment_types>
        <shipping_info>
        </shipping_info>
        <buyer_protection_info>
        </buyer_protection_info>
        <auction_info>
            <current_bid></current_bid>
            <time_left></time_left>
            <high_bidder>
                <bidder_name>BT of Los Angeles</bidder_name>
                <bidder_rating></bidder_rating>
            </high_bidder>
            <num_items>2</num_items>
            <num_bids></num_bids>
            <started_at>$9</started_at>
            <bid_increment>$20</bid_increment>
            <location></location>
            <opened></opened>
            <closed>Mon Nov 27, 2:30 pm PT</closed>
            <id_num>
                3699928
            </id_num>
            <notes></notes>
        </auction_info>
        <bid_history>
            <highest_bid_amount>
                $2475
            </highest_bid_amount>
            <quantity></quantity>
        </bid_history>
        <item_info>
            <memory>AM memory
                expandable to 4GB (128MB
                provided)
            </memory>
            <hard_drive></hard_drive>
            <cpu>800MHz Pentium III processor</cpu>
            <brand></brand>
            <description>Dual processing capability(one
                800MHz Pentium III processor
                providedd)!! RAM memory
                expandable to 4GB (128MB
                provided)!! Refurbished and
                warranted by manufacturer!!HP NetServer LC 2000 Pentium III 800MHz -- The rock-solid
                workgroup server your growing business can depend on --This HP
                NetServer LC 2000 offers an innovative solution that delivers
                top quality to corporate workgroups, branch offices and
                quickly-growing small businesses with: High tech and high
                touch -- designed to be simple to install, configure and
                upgrade, all HP NetServer LC 2000 components are easily
                accessible and designed for tool-less service -- accented by
                color-coded "touch points" High availability -- created to
                deliver the most essential uptime-protecting technologies to
                meet your computing needs. With more hot-swappable and
                redundant components in a workgroup server, the LC 2000
                creates a super-reliable foundation for the growing network
                Intelligent management -- the HP NetServer LC 2000 is
                complemented by a hardware and NOS management suite that
                combines unmatched flexibility with simplicity for precise
                control. HP management tools ensure that your workgroup and
                remote office IT professionals can manage the LC 2000 from any
                location. Best-in-class uptime protection -- with up to six
                hot-swappable disk drive bays, standard redundant,
                hot-swappable fans, optional hot-swappable redundant power
                supplies, support for redundant NICS, and duplexing Freedom
                to expand -- with dual processing capability (one 800MHz
                Pentium III processor provided), capacity for up to 4GB SDRAM
                (128MB standard), expandable storage capability and six open
                PCI slots, the HP NetServer LC 2000 offers room for growth
                that is unprecedented in a workgroup serverThis LC 2000
                provides top quality in a server for corporate workgroups,
                branch offices and quickly growing small businesses that want
                enterprise-level system reliability features. Designed with
                simplicity for easy installation, the HP NetServer LC 2000
                meets the demands of your quickly growing business today and
                offers the capability to expand as your workplace computing
                needs increase in the
                future.********************************** -- F E A T U R E S A
                T A GLANCE --PROCESSOR:One Intel Pentium III 800MHz (dual
                capability with upgrade) with 133MHz front-side bus256K on-die
                write-back cacheMEMORY: Standard: 128MB SDRAM PC-133 DIMM per
                slotMaximum: 4GB Four DIMM sockets HARD DISK DRIVE : Open
                baySTORAGE : Diskette drive: 3.5" 1.44MBCD-ROM drive: Maximum
                32X IDENETWORK CONTROLLER:Integrated 10/100TX NIC (supports
                redundant NICs)BUS SPEED:133MHz front-side bus EXPANSION
                SLOTS:Two 64-bit and four 32-bit PCI slotsPeer 32-bit/64-bit
                PCI buses, both at 33MHzPORTS:One serial portOne 25-pin
                parallel portOne SCSI knockout port for external
                connectionsOne server management port (serial)Video
                port-SVGAMini-DIN keyboard and mouse portsSTORAGE
                CONTROLLER:Embedded dual channel Ultra-2 SCSIVIDEO:Embedded
                ATI Rage IIc video controller1024x768, 64K color at 75Hz2MB
                SGRAMPOWER SUPPLY:349 Watts (Nominal, 100-127/200-240V AC,
                50/60Hz; range, 90-140/180-264V AC, 47/63Hz)FORM
                648mm (25.5") without bezelOPERATING SYSTEM:None installed or
                includedOPTIONAL OPERATING SYSTEMS SUPPORTED:Microsoft Windows
                NT 4.0Windows2000Novell NetWare 4.2, 5.0Red Hat LinuxSCO
                OpenServerUnixWare****************************************HP
                NetServer LC 2000 -- the rock-solid workgroup server your
                growing business can depend on!

            </description>
        </item_info>
    </listing>

    <listing>
        <seller_info>
            <seller_name></seller_name>
            <seller_rating></seller_rating>
        </seller_info>
        <payment_types>
        </payment_types>
        <shipping_info>
        </shipping_info>
        <buyer_protection_info>
        </buyer_protection_info>
        <auction_info>
            <current_bid></current_bid>
            <time_left></time_left>
            <high_bidder>
                <bidder_name>RP of Cleveland</bidder_name>
                <bidder_rating></bidder_rating>
            </high_bidder>
            <num_items>1</num_items>
            <num_bids></num_bids>
            <started_at>$9</started_at>
            <bid_increment>
                $10
            </bid_increment>
            <location></location>
            <opened></opened>
            <closed>Mon Nov 27, 3:00 pm PT</closed>
            <id_num>
                3697285
            </id_num>
            <notes></notes>
        </auction_info>
        <bid_history>
            <highest_bid_amount>$3000
            </highest_bid_amount>
            <quantity></quantity>
        </bid_history>
        <item_info>
            <memory>28MB PC133 SDRAM 168-Pin Memory, 3.3 volt Non-ECC, Non-Buffered, 7.5ns
                Speed
            </memory>
            <hard_drive>30GB 7200 RPM IDE Hard Drive with UltraDMA 66 interface to ensure maximum data
                throughput
            </hard_drive>
            <cpu>III 800MHz Processor with 133MHz Bus</cpu>
            <brand></brand>
            <description>Elite PC PIII 800MHz 128MB RAM 30GB HD 10X DVD
                32MB VID/56K/NIC/3D SND/No OS
            </description>
        </item_info>
    </listing>

    <listing>
        <seller_info>
            <seller_name></seller_name>
            <seller_rating></seller_rating>
        </seller_info>
        <payment_types>
        </payment_types>
        <shipping_info>
        </shipping_info>
        <buyer_protection_info>
        </buyer_protection_info>
        <auction_info>
            <current_bid></current_bid>
            <time_left></time_left>
            <high_bidder>
                <bidder_name></bidder_name>
                <bidder_rating></bidder_rating>
            </high_bidder>
            <num_items></num_items>
            <num_bids></num_bids>
            <started_at></started_at>
            <bid_increment></bid_increment>
            <location></location>
            <opened></opened>
            <closed></closed>
            <id_num></id_num>
            <notes></notes>
        </auction_info>
        <bid_history>
            <highest_bid_amount>
            </highest_bid_amount>
            <quantity></quantity>
        </bid_history>
        <item_info>
            <memory></memory>
            <hard_drive></hard_drive>
            <cpu></cpu>
            <brand></brand>
            <description>
            </description>
        </item_info>
    </listing>

    <listing>
        <seller_info>
            <seller_name></seller_name>
            <seller_rating></seller_rating>
        </seller_info>
        <payment_types>
        </payment_types>
        <shipping_info>
        </shipping_info>
        <buyer_protection_info>
        </buyer_protection_info>
        <auction_info>
            <current_bid></current_bid>
            <time_left></time_left>
            <high_bidder>
                <bidder_name></bidder_name>
                <bidder_rating></bidder_rating>
            </high_bidder>
            <num_items></num_items>
            <num_bids></num_bids>
            <started_at></started_at>
            <bid_increment></bid_increment>
            <location></location>
            <opened></opened>
            <closed></closed>
            <id_num></id_num>
            <notes></notes>
        </auction_info>
        <bid_history>
            <highest_bid_amount>
            </highest_bid_amount>
            <quantity></quantity>
        </bid_history>
        <item_info>
            <memory></memory>
            <hard_drive></hard_drive>
            <cpu></cpu>
            <brand></brand>
            <description>
            </description>
        </item_info>
    </listing>

    <listing>
        <seller_info>
            <seller_name></seller_name>
            <seller_rating></seller_rating>
        </seller_info>
        <payment_types>
        </payment_types>
        <shipping_info>
        </shipping_info>
        <buyer_protection_info>
        </buyer_protection_info>
        <auction_info>
            <current_bid></current_bid>
            <time_left></time_left>
            <high_bidder>
                <bidder_name></bidder_name>
                <bidder_rating></bidder_rating>
            </high_bidder>
            <num_items></num_items>
            <num_bids></num_bids>
            <started_at></started_at>
            <bid_increment></bid_increment>
            <location></location>
            <opened></opened>
            <closed></closed>
            <id_num></id_num>
            <notes></notes>
        </auction_info>
        <bid_history>
            <highest_bid_amount>
            </highest_bid_amount>
            <quantity></quantity>
        </bid_history>
        <item_info>
            <memory></memory>
            <hard_drive></hard_drive>
            <cpu></cpu>
            <brand></brand>
            <description>
            </description>
        </item_info>
    </listing>

    <listing>
        <seller_info>
            <seller_name></seller_name>
            <seller_rating></seller_rating>
        </seller_info>
        <payment_types>
        </payment_types>
        <shipping_info>
        </shipping_info>
        <buyer_protection_info>
        </buyer_protection_info>
        <auction_info>
            <current_bid></current_bid>
            <time_left></time_left>
            <high_bidder>
                <bidder_name></bidder_name>
                <bidder_rating></bidder_rating>
            </high_bidder>
            <num_items></num_items>
            <num_bids></num_bids>
            <started_at></started_at>
            <bid_increment></bid_increment>
            <location></location>
            <opened></opened>
            <closed></closed>
            <id_num></id_num>
            <notes></notes>
        </auction_info>
        <bid_history>
            <highest_bid_amount>
            </highest_bid_amount>
            <quantity></quantity>
        </bid_history>
        <item_info>
            <memory></memory>
            <hard_drive></hard_drive>
            <cpu></cpu>
            <brand></brand>
            <description>
            </description>
        </item_info>
    </listing>
</root>
HTTP 200
