.TH hurl 1 "DATE" "hurl 0.99.13" " Hurl Manual"
.SH NAME

hurlfmt - format Hurl files


.SH SYNOPSIS

.B hurlfmt
[options] [FILE...]


.SH DESCRIPTION

.B hurlfmt
formats Hurl files.



.SH OPTIONS



.IP "--color "

Colorize Output


.IP "-h, --help "

Usage help. This lists all current command line options with a short description.



.IP "--html "

Generate html output.



.IP "-V, --version "

Prints version information




.SH EXIT CODES

.IP "1"
Failed to parse command-line options.


.IP "2"
Input File Parsing Error.


.SH WWW

\fIhttps://hurl.dev\fP


.SH SEE ALSO

hurl(1)


