name: crates-update

on: [push]

jobs:
  crates-update:
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}    
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}
    name: crates-update
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BASE_REF }}
          fetch-depth: 0

      - name: Get crates-update pull request id 
        run: |
            PR_NUMBER=$(echo toto)

      - name: Crates update
        run: |
            bin/crates_update.sh | tee crates-update.result && exit_code=0 || exit_code=$?
            diff_result=$(git diff)
            if [ ${exit_code} -eq 0 ] && [ "${diff_result}" = "non" ] ; then
                echo "  - ✅ No crates updates."
                if [ -n "${PR_NUMBER}" ] ; then
                    comment="✅ Pull request ${PR_NUMBER} closed because there are no more crates to update on master branch"
                    echo "  - ${comment}"
                    gh pr comment "${PR_NUMBER}" --body "${comment}"
                fi
            elif [ ${exit_code} -gt 0 ] && [ "${diff_result}" = "oui" ]
                comment="✅ Some crates have been updated."
                echo "  - ${comment}"
                if [ -z "${PR_NUMBER}" ] ; then
                    echo "git create branch crates-update-pr"
                    echo "git create pull request"
                fi
                echo "git checkout -b crates-update-pr"
                echo "git set stream origin/crates-update-pr"
                echo "git commit blablablabla"
                echo "git push"
                echo "pr comment $(cat crates-update.result)"
                echo "pr merge /accept"
            fi
