name: deliver-release

on:
  workflow_dispatch:

jobs:
  if: github.ref =~ 'refs/heads/release/'
  chocolatey:
    name: chocolatey
    runs-on: windows-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO: ${{ github.repository }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: test
      run: |
        @echo test    
