name: test

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch:
        description: "ref branch for this workflow"
        default: "master"
        required: true
        type: string

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test-docker-archlinux-x64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6.0.1
      with:
        persist-credentials: false
        ref: ${{ inputs.branch }}
    - name: Archlinux
      uses: addnab/docker-run-action@v3
      with:
        image: archlinux
        options: --volume ${{ github.workspace }}:/work --workdir /work --privileged --env CARGO_TERM_COLOR=always
        run: |
          for ipv in 4 6 ; do
              echo "========== ipv${ipv}"
              for count in {1..1000} ; do
                  curl -${ipv} --silent --max-time 1 --http3 --head https://google.com && exit_code=0 || exit_code=1
                  echo "exit_code=$exit_code"
              done > /tmp/log
          done
          grep exit_code /tmp/log | sort | uniq -c
