name: test

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch:
        description: "ref branch for this workflow"
        default: "master"
        required: true
        type: string

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test-macos-aarch64:
    timeout-minutes: 60
    runs-on: getmac
    strategy:
      matrix:
        rust: [stable]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6.0.1
      with:
        persist-credentials: false
        ref: ${{ inputs.branch }}
    - name: Install Prerequisites
      run: |
        bin/install_prerequisites_macos.sh
        echo "PATH=$PATH" >> $GITHUB_ENV
    - name: Activate python3 venv
      run: |
        bin/activate_python3_venv.sh
        export PATH="/tmp/hurl-python3-venv/bin:$PATH"
        echo "PATH=$PATH" >> $GITHUB_ENV
        which python3
        python3 --version
        pip --version
    - name: Install Rust
      run: bin/install_rust.sh
    - name: Environment
      run: bin/environment.sh
    - name: Test Prerequisites
      run: |
        bin/test/test_prerequisites.sh
    - name: Tests units
      run: |
        bin/test/test_unit.sh
        bin/release/release.sh
        echo "PATH=${PWD}/target/release:$PATH" >> "${GITHUB_ENV}"
    - name: Find artifacts
      run: |
        pwd
        find . -name "*.log"
    - name: Archive production artifacts
      uses: actions/upload-artifact@v6.0.0
      if: ${{ always() }}
      with:
        name: tests-macos-aarch64-${{ matrix.rust }}-artifacts
        path: |
          ./**/*.log
